
services:
  db:
    container_name: file-uploader-db
    image: postgres
    environment:
      POSTGRES_USER : postgres
      POSTGRES_PASSWORD : ${POSTGRES_PASSWORD}
      POSTGRES_DB : file-uploader
    ports:
      - "5431:5432"
    volumes:
      - file-uploader-data:/var/lib/postgresql/data

volumes:
  file-uploader-data:
